---
abstract: 'transform xml documents by applying xsl stylesheets on the fly'
author:
  - unknown
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-TazXSLT
provides:
  Plack::Middleware::TazXSLT:
    file: lib/Plack/Middleware/TazXSLT.pm
    version: 0.48
requires:
  Capture::Tiny: 0
  HTTP::Message::PSGI: 0
  HTTP::Response: 0
  LWP::UserAgent: 0
  Plack::Middleware: 0
  Plack::Request: 0
  Plack::Response: 0
  Plack::Util: 0
  Try::Tiny: 0
  URI::QueryParam: 0
  XML::LibXML: 0
  XML::LibXSLT: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.48
x_test_requires:
  Test::MockObject::Extends: 0
  Test::More: 0
